name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: make
    #  run: make
    - name: 检查
      run: make test-output
    - name: Send POST request with JSON data
      run: |
          # 使用 curl 发送 POST 请求
          curl -X POST http://117.72.112.62:8080/api/updateGrade \
            -H "Content-Type: application/json" \
            -d @.build/test_results.json
    - name: 清空
      run: make clean
